-- AlterTable
ALTER TABLE "flexidb"."Bill" ADD COLUMN     "vatPercent" INTEGER,
ALTER COLUMN "total" DROP NOT NULL,
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "totalQuotation" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "beforeDiscount" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "totalAfterTax" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "totalBeforeTax" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "totalTax" SET DATA TYPE DECIMAL(65,30);
