# Define Network
networks:
  prosgres-docker-prisma:
    name: prosgres-docker-prisma
    driver: bridge

# Define Services
services:
  #Postgres Database
  postgresdb:
    image: postgres:15.6
    container_name: flexidb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: prismatypedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 9649:5432
    restart: always
    networks:
      - prosgres-docker-prisma

  # NodeJS Service
  nodejs:
    depends_on:
      - postgresdb
    build:
      context: ./nodejs
    image: node:18-alpine
    container_name: nodejsexpress
    volumes:
     - .:/app # Mount the entire project directory to /app in the container
     - /app/node_modules # Prevent overwriting node_modules in the container
    working_dir: /app
    command: sh -c "npm install && npm run dev" # Ensure devDependencies are installed
    ports:
      - 4000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgresdb:5432/prismatypedb
      - NODE_ENV=development
    restart: always
    networks:
      - prosgres-docker-prisma
